openapi: 3.0.3
info:
  title: Time Tracker API
  description: REST API for the Time Tracker application
  version: 1.0.0
  contact:
    name: Time Tracker Team
    email: support@timetracker.com

servers:
  - url: http://localhost:8080
    description: Development server

paths:
  /trackers:
    get:
      summary: Get all time tracking entries
      description: Retrieves all time tracking entries from the database
      tags:
        - Trackers
      responses:
        '200':
          description: List of time tracking entries
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Tracker'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
    post:
      summary: Create a new time tracking entry
      description: Creates a new time tracking entry in the database (Currently not implemented)
      tags:
        - Trackers
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTracker'
      responses:
        '201':
          description: Time tracking entry created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tracker'
        '501':
          description: Not implemented yet
          content:
            application/json:
              schema:
                type: string
                example: "Not Implemented Yet"

  /trackers/{id}:
    get:
      summary: Get time tracking entry by ID
      description: Retrieves a specific time tracking entry by its ID (Currently not implemented)
      tags:
        - Trackers
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the time tracking entry
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Time tracking entry found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tracker'
        '404':
          description: Time tracking entry not found
        '501':
          description: Not implemented yet
          content:
            application/json:
              schema:
                type: string
                example: "Not Implemented Yet: 1"
    put:
      summary: Update time tracking entry
      description: Updates an existing time tracking entry by ID (Currently not implemented)
      tags:
        - Trackers
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the time tracking entry to update
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UpdateTracker'
      responses:
        '200':
          description: Time tracking entry updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Tracker'
        '404':
          description: Time tracking entry not found
        '501':
          description: Not implemented yet
          content:
            application/json:
              schema:
                type: string
                example: "Not Implemented Yet: 1"
    delete:
      summary: Delete time tracking entry
      description: Removes a time tracking entry from the database by ID (Currently not implemented)
      tags:
        - Trackers
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the time tracking entry to delete
          schema:
            type: integer
            example: 1
      responses:
        '204':
          description: Time tracking entry deleted successfully
        '404':
          description: Time tracking entry not found
        '501':
          description: Not implemented yet
          content:
            application/json:
              schema:
                type: string
                example: "Not Implemented Yet: 1"

  /health:
    get:
      summary: Health check endpoint
      description: Returns the health status of the API server
      tags:
        - Health
      responses:
        '200':
          description: Server is healthy
          content:
            text/plain:
              schema:
                type: string
                example: "OK"

components:
  schemas:
    Tracker:
      type: object
      description: Time tracking entry representing a work session
      properties:
        id:
          type: integer
          description: Unique identifier for the time tracking entry
          example: 1
        task:
          type: string
          description: Description of the task being tracked
          example: "Development work on user authentication"
        start_time:
          type: string
          description: Start time of the work session (stored as string in current implementation)
          example: "2025-10-11T09:00:00Z"
        end_time:
          type: string
          description: End time of the work session (stored as string in current implementation)
          example: "2025-10-11T17:00:00Z"
      required:
        - id
        - task
        - start_time
        - end_time

    CreateTracker:
      type: object
      description: Data required to create a new time tracking entry
      properties:
        task:
          type: string
          description: Description of the task to be tracked
          example: "Development work on user authentication"
          minLength: 1
          maxLength: 500
        start_time:
          type: string
          description: Start time of the work session
          example: "2025-10-11T09:00:00Z"
        end_time:
          type: string
          description: End time of the work session (optional for ongoing tasks)
          example: "2025-10-11T17:00:00Z"
      required:
        - task
        - start_time

    UpdateTracker:
      type: object
      description: Data that can be updated for an existing time tracking entry
      properties:
        task:
          type: string
          description: Updated description of the task
          example: "Development work on user authentication - completed"
          minLength: 1
          maxLength: 500
        start_time:
          type: string
          description: Updated start time of the work session
          example: "2025-10-11T09:00:00Z"
        end_time:
          type: string
          description: Updated end time of the work session
          example: "2025-10-11T17:00:00Z"

    Error:
      type: object
      description: Standard error response format
      properties:
        error:
          type: string
          description: Human-readable error message
          example: "Failed to fetch trackers"
        code:
          type: string
          description: Error code for programmatic handling
          example: "DATABASE_ERROR"
        timestamp:
          type: string
          format: date-time
          description: When the error occurred
          example: "2025-10-11T10:30:00Z"
